menus:
  default:
    title: "<bold>Interact with <target>"
    options:
      - name: "Say hello!"
        material: "RED_DYE"
        offset: [0, 0.5, 0]
        command: "msg <target> hello!"
        interactable: true
      - name: "Ban <target>"
        material: "DIAMOND_SWORD"
        offset: [0, 1.25, 0]
        command: "ban <target>"
        interactable: true
      - name: "Add friend"
        material: "BLACK_DYE"
        offset: [0, 2, 0]
        command: "friend add <target>"
        interactable: true