menus:
  default:
    title: "Main Menu"
    options:
      - name: "<bold>Report"
        material: "RED_DYE"
        offset: [0, 0.5, 0]
        command: "report <target>"
      - name: "<bold>Challenge"
        material: "DIAMOND_SWORD"
        offset: [0, 1.25, 0]
        command: "challenge <target>"
      - name: "<bold>Add friend"
        material: "BLACK_DYE"
        offset: [0, 2, 0]
        command: "friend add <target>"