name: PaperGUI
version: '1.0'
main: dev.aquestry.paperGUI.PaperGUI
api-version: '1.21'
authors: [ Aquestry ]
website: https://aquestry.dev

commands:
  reload-ppgui:
    description: Reloads the config.
    permission: ppgui.command.reload
    usage: /reload-ppgui